Document: datapacker
Title: Debian datapacker Manual
Author: <insert document author here>
Abstract: This manual describes what datapacker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/datapacker/datapacker.sgml.gz

Format: postscript
Files: /usr/share/doc/datapacker/datapacker.ps.gz

Format: text
Files: /usr/share/doc/datapacker/datapacker.text.gz

Format: HTML
Index: /usr/share/doc/datapacker/html/index.html
Files: /usr/share/doc/datapacker/html/*.html

  
